version: '3.8'

services:
  # FRONT
  autenticacion:
    build: ./ServicioAutenticacion
    container_name: ServAutenticacion
    ports:
      - "8081:80"

 
  gestion_notas:
    build: ./ServicioGestionNotas
    container_name: ServGestionNotas
    ports:
      - "8082:80"

  
  papelera:
    build: ./ServicioPapelera
    container_name: ServPapelera
    ports:
      - "8083:80"

  

  # SERVICIO BASE DE DATOS
  bd_proyectonotas:
    image: mysql
    container_name: bd_proyectoNotas
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=sistemaNotasBd
    ports:
      - "3306:3306"


  # BACK
  # 4. Servicio Backend
  servicio_back_node:
    build: ./ServicioBackend
    container_name: backend_node
    ports:
      - "3000:3000"
    depends_on:
      - bd_proyectonotas